apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: invalid component
  description: An Invalid Component with a name that doesn't comply to the restrictions
  labels:
    goVersion: go1.15.3
    category: music
  tags:
    - go
    - go 1.15.3
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
